#!/usr/bin/env bash
# Script that displays hours from 0 to 12 and minutes from 1 to 59 with while loop.

h=0
m=1
while [ $h -le 12 ]; do
	echo "Hour: $h"
	m=1
	while [ $m -lt 60 ]; do
		echo "$m"
		m=$((m+1))
	done

	h=$((h+1))
done
