#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.

cp /etc/hosts /etc/hosts.old
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
