#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.

cp /etc/hosts /etc/hosts.old
sed -i -e 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/g' -e '$a\8.8.8.8	facebook.com' /etc/hosts
