#!/usr/bin/env bash
# script that configures the server to run on port 80.
sudo useradd --no-create-home --shell /bin/bash --system --password '*' nginx
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
