#!/usr/bin/env bash

# command to connect the user `ubuntu` with the server `54.144.153.224`
# by the Secure Shell using public key in file `~/.ssh/school`.
ssh -i ~/.ssh/school ubuntu@35.175.105.245
